apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/atp-user-consumer
  newTag: 103eda26


configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: atp-user-consumer-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: atp-user-consumer-secret-env
