apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: atp-training

images:
- name: asia.gcr.io/poc-innovation-iot/atp-admin-authen
  newTag: 1ad33d02


configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: atp-admin-authen-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: atp-admin-authen-secret-env
