apiVersion: apps/v1
kind: Deployment
metadata:
  name: atp-admin-authen
  labels:
    app.kubernetes.io/name: atp-admin-authen
    app.kubernetes.io/instance: atp-admin-authen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: atp-admin-authen
      app.kubernetes.io/instance: atp-admin-authen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atp-admin-authen
        app.kubernetes.io/instance: atp-admin-authen
    spec:
      containers:
        - name: atp-admin-authen
          image: asia.gcr.io/poc-innovation-iot/atp-admin-authen:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: atp-admin-authen-secret-env
          volumeMounts:
              - mountPath: /config/config.yaml
                name: atp-admin-authen-configmap-file
                subPath: config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: atp-admin-authen-secret-file
          secret:
            secretName: atp-admin-authen-secret-file
        - name: atp-admin-authen-configmap-file
          configMap:
            name: atp-admin-authen-configmap-file